spring.application.name=pedido-service
spring.grpc.server.port=9090
spring.grpc.client.channel.estoque.target=static://localhost:9091

spring.main.web-application-type=none

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
